#Dictates which side of the screen the encumbrance bar should render on.
#Allowed Values: LEFT, RIGHT, CENTER, NONE
WeightBarRenderSide = "LEFT"
#Dictates the style of bar that should be rendered.
#Allowed Values: VERTICAL, HORIZONTAL
WeightBarRenderStyle = "VERTICAL"
#Dictates the color of the weight bar when the player is not encumbered.
#Allowed Values: BLACK, WHITE, RED, GREEN, BLUE, YELLOW, ORANGE, PURPLE
WeightBarNotEncumberedColor = "GREEN"
#Dictates the color of the weight bar when the player is encumbered.
#Allowed Values: BLACK, WHITE, RED, GREEN, BLUE, YELLOW, ORANGE, PURPLE
WeightBarEncumberedColor = "YELLOW"
#Dictates the color of the weight bar when the player is over encumbered.
#Allowed Values: BLACK, WHITE, RED, GREEN, BLUE, YELLOW, ORANGE, PURPLE
WeightBarOverEncumberedColor = "RED"
#Dictates if the player weight text should be shown.
ShowWeightText = true
#Dictates if the weight bar should render.
ShowWeightBar = true

