name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Managing issues helps us create a better experience for users! Thank you for helping out."
        pr-message: "Thanks for creating a Pull Request for Heavy Inventories!"
